# Autogenerated wrapper script for StreamVByte_jll for armv7l-linux-gnueabihf
export libstreamvbyte

JLLWrappers.@generate_wrapper_header("StreamVByte")
JLLWrappers.@declare_library_product(libstreamvbyte, "libstreamvbyte.so.2")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libstreamvbyte,
        "lib/libstreamvbyte.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
