# Autogenerated wrapper script for StreamVByte_jll for x86_64-apple-darwin
export libstreamvbyte

JLLWrappers.@generate_wrapper_header("StreamVByte")
JLLWrappers.@declare_library_product(libstreamvbyte, "@rpath/libstreamvbyte.2.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libstreamvbyte,
        "lib/libstreamvbyte.2.0.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
