# Autogenerated wrapper script for StreamVByte_jll for x86_64-w64-mingw32
export libstreamvbyte

JLLWrappers.@generate_wrapper_header("StreamVByte")
JLLWrappers.@declare_library_product(libstreamvbyte, "libstreamvbyte.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libstreamvbyte,
        "bin\\libstreamvbyte.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
